export const STATUS = {
    inactive: 'inactive',
    active: 'active'
}

export const CURRENCY = {
    "AED": { "name": "United Arab Emirates Dirham", "symbol": "د.إ" },
    "AFN": { "name": "Afghan Afghani", "symbol": "؋" },
    "ALL": { "name": "Albanian Lek", "symbol": "Lek" },
    "AMD": { "name": "Armenian Dram", "symbol": "֏" },
    "ANG": { "name": "Netherlands Antillean Guilder", "symbol": "ƒ" },
    "AOA": { "name": "Angolan Kwanza", "symbol": "Kz" },
    "ARS": { "name": "Argentine Peso", "symbol": "$" },
    "AUD": { "name": "Australian Dollar", "symbol": "$" },
    "AWG": { "name": "Aruban Florin", "symbol": "ƒ" },
    "AZN": { "name": "Azerbaijani Manat", "symbol": "₼" },
    "BAM": { "name": "Bosnia-Herzegovina Convertible Mark", "symbol": "KM" },
    "BBD": { "name": "Barbadian Dollar", "symbol": "$" },
    "BDT": { "name": "Bangladeshi Taka", "symbol": "৳" },
    "BGN": { "name": "Bulgarian Lev", "symbol": "лв" },
    "BHD": { "name": "Bahraini Dinar", "symbol": "ب.د" },
    "BIF": { "name": "Burundian Franc", "symbol": "FBu" },
    "BMD": { "name": "Bermudan Dollar", "symbol": "$" },
    "BND": { "name": "Brunei Dollar", "symbol": "$" },
    "BOB": { "name": "Bolivian Boliviano", "symbol": "Bs." },
    "BRL": { "name": "Brazilian Real", "symbol": "R$" },
    "BSD": { "name": "Bahamian Dollar", "symbol": "$" },
    "BTC": { "name": "Bitcoin", "symbol": "₿" },
    "BTN": { "name": "Bhutanese Ngultrum", "symbol": "Nu." },
    "BWP": { "name": "Botswanan Pula", "symbol": "P" },
    "BYN": { "name": "Belarusian Ruble", "symbol": "Br" },
    "BZD": { "name": "Belize Dollar", "symbol": "BZ$" },
    "CAD": { "name": "Canadian Dollar", "symbol": "$" },
    "CDF": { "name": "Congolese Franc", "symbol": "FC" },
    "CHF": { "name": "Swiss Franc", "symbol": "CHF" },
    "CLF": { "name": "Chilean Unit of Account (UF)", "symbol": "UF" },
    "CLP": { "name": "Chilean Peso", "symbol": "$" },
    "CNH": { "name": "Chinese Yuan (Offshore)", "symbol": "CN¥" },
    "CNY": { "name": "Chinese Yuan", "symbol": "¥" },
    "COP": { "name": "Colombian Peso", "symbol": "$" },
    "CRC": { "name": "Costa Rican Colón", "symbol": "₡" },
    "CUC": { "name": "Cuban Convertible Peso", "symbol": "CUC" },
    "CUP": { "name": "Cuban Peso", "symbol": "₱" },
    "CVE": { "name": "Cape Verdean Escudo", "symbol": "$" },
    "CZK": { "name": "Czech Republic Koruna", "symbol": "Kč" },
    "DJF": { "name": "Djiboutian Franc", "symbol": "Fdj" },
    "DKK": { "name": "Danish Krone", "symbol": "kr" },
    "DOP": { "name": "Dominican Peso", "symbol": "RD$" },
    "DZD": { "name": "Algerian Dinar", "symbol": "د.ج" },
    "EGP": { "name": "Egyptian Pound", "symbol": "£" },
    "ERN": { "name": "Eritrean Nakfa", "symbol": "Nfk" },
    "ETB": { "name": "Ethiopian Birr", "symbol": "Br" },
    "EUR": { "name": "Euro", "symbol": "€" },
    "FJD": { "name": "Fijian Dollar", "symbol": "$" },
    "FKP": { "name": "Falkland Islands Pound", "symbol": "£" },
    "GBP": { "name": "British Pound Sterling", "symbol": "£" },
    "GEL": { "name": "Georgian Lari", "symbol": "₾" },
    "GGP": { "name": "Guernsey Pound", "symbol": "£" },
    "GHS": { "name": "Ghanaian Cedi", "symbol": "₵" },
    "GIP": { "name": "Gibraltar Pound", "symbol": "£" },
    "GMD": { "name": "Gambian Dalasi", "symbol": "D" },
    "GNF": { "name": "Guinean Franc", "symbol": "FG" },
    "GTQ": { "name": "Guatemalan Quetzal", "symbol": "Q" },
    "GYD": { "name": "Guyanaese Dollar", "symbol": "$" },
    "HKD": { "name": "Hong Kong Dollar", "symbol": "HK$" },
    "HNL": { "name": "Honduran Lempira", "symbol": "L" },
    "HRK": { "name": "Croatian Kuna", "symbol": "kn" },
    "HTG": { "name": "Haitian Gourde", "symbol": "G" },
    "HUF": { "name": "Hungarian Forint", "symbol": "Ft" },
    "IDR": { "name": "Indonesian Rupiah", "symbol": "Rp" },
    "ILS": { "name": "Israeli New Sheqel", "symbol": "₪" },
    "IMP": { "name": "Isle of Man Pound", "symbol": "£" },
    "INR": { "name": "Indian Rupee", "symbol": "₹" },
    "IQD": { "name": "Iraqi Dinar", "symbol": "ع.د" },
    "IRR": { "name": "Iranian Rial", "symbol": "﷼" },
    "ISK": { "name": "Icelandic Króna", "symbol": "kr" },
    "JEP": { "name": "Jersey Pound", "symbol": "£" },
    "JMD": { "name": "Jamaican Dollar", "symbol": "J$" },
    "JOD": { "name": "Jordanian Dinar", "symbol": "د.ا" },
    "JPY": { "name": "Japanese Yen", "symbol": "¥" },
    "KES": { "name": "Kenyan Shilling", "symbol": "KSh" },
    "KGS": { "name": "Kyrgystani Som", "symbol": "с" },
    "KHR": { "name": "Cambodian Riel", "symbol": "៛" },
    "KID": { "name": "Kiribati Dollar", "symbol": "$" },
    "KMF": { "name": "Comorian Franc", "symbol": "CF" },
    "KRW": { "name": "South Korean Won", "symbol": "₩" },
    "KWD": { "name": "Kuwaiti Dinar", "symbol": "د.ك" },
    "KYD": { "name": "Cayman Islands Dollar", "symbol": "$" },
    "KZT": { "name": "Kazakhstani Tenge", "symbol": "₸" },
    "LAK": { "name": "Laotian Kip", "symbol": "₭" },
    "LBP": { "name": "Lebanese Pound", "symbol": "ل.ل" },
    "LKR": { "name": "Sri Lankan Rupee", "symbol": "Rs" },
    "LRD": { "name": "Liberian Dollar", "symbol": "$" },
    "LSL": { "name": "Lesotho Loti", "symbol": "L" },
    "LYD": { "name": "Libyan Dinar", "symbol": "ل.د" },
    "MAD": { "name": "Moroccan Dirham", "symbol": "د.م." },
    "MDL": { "name": "Moldovan Leu", "symbol": "L" },
    "MGA": { "name": "Malagasy Ariary", "symbol": "Ar" },
    "MKD": { "name": "Macedonian Denar", "symbol": "ден" },
    "MMK": { "name": "Myanmar Kyat", "symbol": "Ks" },
    "MNT": { "name": "Mongolian Tugrik", "symbol": "₮" },
    "MOP": { "name": "Macanese Pataca", "symbol": "MOP$" },
    "MRU": { "name": "Mauritanian Ouguiya", "symbol": "UM" },
    "MUR": { "name": "Mauritian Rupee", "symbol": "₨" },
    "MVR": { "name": "Maldivian Rufiyaa", "symbol": "Rf" },
    "MWK": { "name": "Malawian Kwacha", "symbol": "MK" },
    "MXN": { "name": "Mexican Peso", "symbol": "$" },
    "MYR": { "name": "Malaysian Ringgit", "symbol": "RM" },
    "MZN": { "name": "Mozambican Metical", "symbol": "MT" },
    "NAD": { "name": "Namibian Dollar", "symbol": "$" },
    "NGN": { "name": "Nigerian Naira", "symbol": "₦" },
    "NIO": { "name": "Nicaraguan Córdoba", "symbol": "C$" },
    "NOK": { "name": "Norwegian Krone", "symbol": "kr" },
    "NPR": { "name": "Nepalese Rupee", "symbol": "₨" },
    "NZD": { "name": "New Zealand Dollar", "symbol": "$" },
    "OMR": { "name": "Omani Rial", "symbol": "ر.ع." },
    "PAB": { "name": "Panamanian Balboa", "symbol": "B/." },
    "PEN": { "name": "Peruvian Nuevo Sol", "symbol": "S/." },
    "PGK": { "name": "Papua New Guinean Kina", "symbol": "K" },
    "PHP": { "name": "Philippine Peso", "symbol": "₱" },
    "PKR": { "name": "Pakistani Rupee", "symbol": "₨" },
    "PLN": { "name": "Polish Zloty", "symbol": "zł" },
    "PYG": { "name": "Paraguayan Guarani", "symbol": "₲" },
    "QAR": { "name": "Qatari Rial", "symbol": "ر.ق" },
    "RON": { "name": "Romanian Leu", "symbol": "lei" },
    "RSD": { "name": "Serbian Dinar", "symbol": "дин." },
    "RUB": { "name": "Russian Ruble", "symbol": "₽" },
    "RWF": { "name": "Rwandan Franc", "symbol": "FR" },
    "SAR": { "name": "Saudi Riyal", "symbol": "ر.س" },
    "SBD": { "name": "Solomon Islands Dollar", "symbol": "$" },
    "SCR": { "name": "Seychellois Rupee", "symbol": "₨" },
    "SDG": { "name": "Sudanese Pound", "symbol": "ج.س" },
    "SEK": { "name": "Swedish Krona", "symbol": "kr" },
    "SGD": { "name": "Singapore Dollar", "symbol": "$" },
    "SHP": { "name": "Saint Helena Pound", "symbol": "£" },
    "SLL": { "name": "Sierra Leonean Leone", "symbol": "Le" },
    "SOS": { "name": "Somali Shilling", "symbol": "Sh" },
    "SRD": { "name": "Surinamese Dollar", "symbol": "$" },
    "SSP": { "name": "South Sudanese Pound", "symbol": "£" },
    "STN": { "name": "São Tomé and Príncipe Dobra", "symbol": "Db" },
    "SYP": { "name": "Syrian Pound", "symbol": "£" },
    "SZL": { "name": "Swazi Lilangeni", "symbol": "L" },
    "THB": { "name": "Thai Baht", "symbol": "฿" },
    "TJS": { "name": "Tajikistani Somoni", "symbol": "ЅМ" },
    "TMT": { "name": "Turkmenistani Manat", "symbol": "T" },
    "TND": { "name": "Tunisian Dinar", "symbol": "د.ت" },
    "TOP": { "name": "Tongan Pa'anga", "symbol": "T$" },
    "TRY": { "name": "Turkish Lira", "symbol": "₺" },
    "TTD": { "name": "Trinidad and Tobago Dollar", "symbol": "TT$" },
    "TWD": { "name": "New Taiwan Dollar", "symbol": "NT$" },
    "TZS": { "name": "Tanzanian Shilling", "symbol": "Sh" },
    "UAH": { "name": "Ukrainian Hryvnia", "symbol": "₴" },
    "UGX": { "name": "Ugandan Shilling", "symbol": "USh" },
    "USD": { "name": "United States Dollar", "symbol": "$" },
    "UYU": { "name": "Uruguayan Peso", "symbol": "$U" },
    "UZS": { "name": "Uzbekistan Som", "symbol": "so'm" },
    "VES": { "name": "Venezuelan Bolívar", "symbol": "Bs.S." },
    "VND": { "name": "Vietnamese Dong", "symbol": "₫" },
    "VUV": { "name": "Vanuatu Vatu", "symbol": "Vt" },
    "WST": { "name": "Samoan Tala", "symbol": "T" },
    "XAF": { "name": "CFA Franc BEAC", "symbol": "FCFA" },
    "XAG": { "name": "Silver Ounce", "symbol": "XAG" },
    "XAU": { "name": "Gold Ounce", "symbol": "XAU" },
    "XCD": { "name": "East Caribbean Dollar", "symbol": "$" },
    "XDR": { "name": "Special Drawing Rights", "symbol": "SDR" },
    "XOF": { "name": "CFA Franc BCEAO", "symbol": "CFA" },
    "XPD": { "name": "Palladium Ounce", "symbol": "XPD" },
    "XPF": { "name": "CFP Franc", "symbol": "CFPF" },
    "XPT": { "name": "Platinum Ounce", "symbol": "XPT" },
    "YER": { "name": "Yemeni Rial", "symbol": "﷼" },
    "ZAR": { "name": "South African Rand", "symbol": "R" },
    "ZMW": { "name": "Zambian Kwacha", "symbol": "ZK" },
    "ZWL": { "name": "Zimbabwean Dollar", "symbol": "Z$" }
};

  export const LANGUAGES = [
    { "code": "aa", "name": "Afar" },
    { "code": "ab", "name": "Abkhazian" },
    { "code": "ae", "name": "Avestan" },
    { "code": "af", "name": "Afrikaans" },
    { "code": "ak", "name": "Akan" },
    { "code": "am", "name": "Amharic" },
    { "code": "an", "name": "Aragonese" },
    { "code": "ar", "name": "Arabic" },
    { "code": "as", "name": "Assamese" },
    { "code": "av", "name": "Avaric" },
    { "code": "ay", "name": "Aymara" },
    { "code": "az", "name": "Azerbaijani" },
    { "code": "ba", "name": "Bashkir" },
    { "code": "be", "name": "Belarusian" },
    { "code": "bg", "name": "Bulgarian" },
    { "code": "bh", "name": "Bihari languages" },
    { "code": "bi", "name": "Bislama" },
    { "code": "bm", "name": "Bambara" },
    { "code": "bn", "name": "Bengali" },
    { "code": "bo", "name": "Tibetan" },
    { "code": "br", "name": "Breton" },
    { "code": "bs", "name": "Bosnian" },
    { "code": "ca", "name": "Catalan; Valencian" },
    { "code": "ce", "name": "Chechen" },
    { "code": "ch", "name": "Chamorro" },
    { "code": "co", "name": "Corsican" },
    { "code": "cr", "name": "Cree" },
    { "code": "cs", "name": "Czech" },
    {
      "code": "cu",
      "name": "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"
    },
    { "code": "cv", "name": "Chuvash" },
    { "code": "cy", "name": "Welsh" },
    { "code": "da", "name": "Danish" },
    { "code": "de", "name": "German" },
    { "code": "dv", "name": "Divehi; Dhivehi; Maldivian" },
    { "code": "dz", "name": "Dzongkha" },
    { "code": "ee", "name": "Ewe" },
    { "code": "el", "name": "Greek, Modern (1453-)" },
    { "code": "en", "name": "English" },
    { "code": "eo", "name": "Esperanto" },
    { "code": "es", "name": "Spanish; Castilian" },
    { "code": "et", "name": "Estonian" },
    { "code": "eu", "name": "Basque" },
    { "code": "fa", "name": "Persian" },
    { "code": "ff", "name": "Fulah" },
    { "code": "fi", "name": "Finnish" },
    { "code": "fj", "name": "Fijian" },
    { "code": "fo", "name": "Faroese" },
    { "code": "fr", "name": "French" },
    { "code": "fy", "name": "Western Frisian" },
    { "code": "ga", "name": "Irish" },
    { "code": "gd", "name": "Gaelic; Scomttish Gaelic" },
    { "code": "gl", "name": "Galician" },
    { "code": "gn", "name": "Guarani" },
    { "code": "gu", "name": "Gujarati" },
    { "code": "gv", "name": "Manx" },
    { "code": "ha", "name": "Hausa" },
    { "code": "he", "name": "Hebrew" },
    { "code": "hi", "name": "Hindi" },
    { "code": "ho", "name": "Hiri Motu" },
    { "code": "hr", "name": "Croatian" },
    { "code": "ht", "name": "Haitian; Haitian Creole" },
    { "code": "hu", "name": "Hungarian" },
    { "code": "hy", "name": "Armenian" },
    { "code": "hz", "name": "Herero" },
    {
      "code": "ia",
      "name": "Interlingua (International Auxiliary Language Association)"
    },
    { "code": "id", "name": "Indonesian" },
    { "code": "ie", "name": "Interlingue; Occidental" },
    { "code": "ig", "name": "Igbo" },
    { "code": "ii", "name": "Sichuan Yi; Nuosu" },
    { "code": "ik", "name": "Inupiaq" },
    { "code": "io", "name": "Ido" },
    { "code": "is", "name": "Icelandic" },
    { "code": "it", "name": "Italian" },
    { "code": "iu", "name": "Inuktitut" },
    { "code": "ja", "name": "Japanese" },
    { "code": "jv", "name": "Javanese" },
    { "code": "ka", "name": "Georgian" },
    { "code": "kg", "name": "Kongo" },
    { "code": "ki", "name": "Kikuyu; Gikuyu" },
    { "code": "kj", "name": "Kuanyama; Kwanyama" },
    { "code": "kk", "name": "Kazakh" },
    { "code": "kl", "name": "Kalaallisut; Greenlandic" },
    { "code": "km", "name": "Central Khmer" },
    { "code": "kn", "name": "Kannada" },
    { "code": "ko", "name": "Korean" },
    { "code": "kr", "name": "Kanuri" },
    { "code": "ks", "name": "Kashmiri" },
    { "code": "ku", "name": "Kurdish" },
    { "code": "kv", "name": "Komi" },
    { "code": "kw", "name": "Cornish" },
    { "code": "ky", "name": "Kirghiz; Kyrgyz" },
    { "code": "la", "name": "Latin" },
    { "code": "lb", "name": "Luxembourgish; Letzeburgesch" },
    { "code": "lg", "name": "Ganda" },
    { "code": "li", "name": "Limburgan; Limburger; Limburgish" },
    { "code": "ln", "name": "Lingala" },
    { "code": "lo", "name": "Lao" },
    { "code": "lt", "name": "Lithuanian" },
    { "code": "lu", "name": "Luba-Katanga" },
    { "code": "lv", "name": "Latvian" },
    { "code": "mg", "name": "Malagasy" },
    { "code": "mh", "name": "Marshallese" },
    { "code": "mi", "name": "Maori" },
    { "code": "mk", "name": "Macedonian" },
    { "code": "ml", "name": "Malayalam" },
    { "code": "mn", "name": "Mongolian" },
    { "code": "mr", "name": "Marathi" },
    { "code": "ms", "name": "Malay" },
    { "code": "mt", "name": "Maltese" },
    { "code": "my", "name": "Burmese" },
    { "code": "na", "name": "Nauru" },
    { "code": "nb", "name": "Bokmål, Norwegian; Norwegian Bokmål" },
    { "code": "nd", "name": "Ndebele, North; North Ndebele" },
    { "code": "ne", "name": "Nepali" },
    { "code": "ng", "name": "Ndonga" },
    { "code": "nl", "name": "Dutch; Flemish" },
    { "code": "nn", "name": "Norwegian Nynorsk; Nynorsk, Norwegian" },
    { "code": "no", "name": "Norwegian" },
    { "code": "nr", "name": "Ndebele, South; South Ndebele" },
    { "code": "nv", "name": "Navajo; Navaho" },
    { "code": "ny", "name": "Chichewa; Chewa; Nyanja" },
    { "code": "oc", "name": "Occitan (post 1500)" },
    { "code": "oj", "name": "Ojibwa" },
    { "code": "om", "name": "Oromo" },
    { "code": "or", "name": "Oriya" },
    { "code": "os", "name": "Ossetian; Ossetic" },
    { "code": "pa", "name": "Panjabi; Punjabi" },
    { "code": "pi", "name": "Pali" },
    { "code": "pl", "name": "Polish" },
    { "code": "ps", "name": "Pushto; Pashto" },
    { "code": "pt", "name": "Portuguese" },
    { "code": "qu", "name": "Quechua" },
    { "code": "rm", "name": "Romansh" },
    { "code": "rn", "name": "Rundi" },
    { "code": "ro", "name": "Romanian; Moldavian; Moldovan" },
    { "code": "ru", "name": "Russian" },
    { "code": "rw", "name": "Kinyarwanda" },
    { "code": "sa", "name": "Sanskrit" },
    { "code": "sc", "name": "Sardinian" },
    { "code": "sd", "name": "Sindhi" },
    { "code": "se", "name": "Northern Sami" },
    { "code": "sg", "name": "Sango" },
    { "code": "si", "name": "Sinhala; Sinhalese" },
    { "code": "sk", "name": "Slovak" },
    { "code": "sl", "name": "Slovenian" },
    { "code": "sm", "name": "Samoan" },
    { "code": "sn", "name": "Shona" },
    { "code": "so", "name": "Somali" },
    { "code": "sq", "name": "Albanian" },
    { "code": "sr", "name": "Serbian" },
    { "code": "ss", "name": "Swati" },
    { "code": "st", "name": "Sotho, Southern" },
    { "code": "su", "name": "Sundanese" },
    { "code": "sv", "name": "Swedish" },
    { "code": "sw", "name": "Swahili" },
    { "code": "ta", "name": "Tamil" },
    { "code": "te", "name": "Telugu" },
    { "code": "tg", "name": "Tajik" },
    { "code": "th", "name": "Thai" },
    { "code": "ti", "name": "Tigrinya" },
    { "code": "tk", "name": "Turkmen" },
    { "code": "tl", "name": "Tagalog" },
    { "code": "tn", "name": "Tswana" },
    { "code": "to", "name": "Tonga (Tonga Islands)" },
    { "code": "tr", "name": "Turkish" },
    { "code": "ts", "name": "Tsonga" },
    { "code": "tt", "name": "Tatar" },
    { "code": "tw", "name": "Twi" },
    { "code": "ty", "name": "Tahitian" },
    { "code": "ug", "name": "Uighur; Uyghur" },
    { "code": "uk", "name": "Ukrainian" },
    { "code": "ur", "name": "Urdu" },
    { "code": "uz", "name": "Uzbek" },
    { "code": "ve", "name": "Venda" },
    { "code": "vi", "name": "Vietnamese" },
    { "code": "vo", "name": "Volapük" },
    { "code": "wa", "name": "Walloon" },
    { "code": "wo", "name": "Wolof" },
    { "code": "xh", "name": "Xhosa" },
    { "code": "yi", "name": "Yiddish" },
    { "code": "yo", "name": "Yoruba" },
    { "code": "za", "name": "Zhuang; Chuang" },
    { "code": "zh", "name": "Chinese" },
    { "code": "zu", "name": "Zulu" }
  ]